import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Plus_Jakarta_Sans as FontSans } from 'next/font/google';

import { ModalProvider } from '~/components/providers/modal-provider';
import { ThemeProvider } from '~/components/providers/theme-provider';
import { Toaster } from '~/components/ui/toaster';
import { cn } from '~/lib/utils';
import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
  title: 'Kanban Task Management',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({
  children,
  taskModal,
}: {
  children: React.ReactNode;
  taskModal: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <TRPCReactProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            {children}
            {taskModal}
            <ModalProvider />
            <Toaster />
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
